#ifndef DEF_H_
#define DEF_H_

#define WND_CLASS_NAME L"brainfuck-main"
#define APP_NAME L"Brainfuck interpreter for SHARP Brain"
#define APP_VERSION L"0.1"
#define WM_APP_THREADEND WM_APP
#define IDT_RUN 1

#define VER_STR_COMPANYNAME "watamario15"
#define VER_STR_DESCRIPTION "Brainfuck interpreter for SHARP Brain"
#define VER_STR_FILEVERSION 0, 1, 0, 0
#define VER_STR_APPNAME "Brainfuck interpreter for SHARP Brain"
#define VER_STR_COPYRIGHT "(C) 2022 watamario15"
#define VER_STR_ORIGINALFILENAME "Brainfuck.exe"
#define VER_STR_VERSION "0.1"

#define IDC_EDITOR 0
#define IDC_INPUT 1
#define IDC_OUTPUT 2
#define IDC_CMDBTN_FIRST 3
#define IDC_SCRKBD_FIRST 7

#define IDM_FILE_NEW 1000
#define IDM_FILE_OPEN 1001
#define IDM_FILE_SAVE 1002
#define IDM_FILE_SAVE_AS 1003
#define IDM_FILE_EXIT 1004
#define IDM_OPT_SPEED_FASTEST 1100
#define IDM_OPT_SPEED_1MS 1101
#define IDM_OPT_SPEED_10MS 1102
#define IDM_OPT_SPEED_100MS 1103
#define IDM_OPT_MEMTYPE_SIGNED 1110
#define IDM_OPT_MEMTYPE_UNSIGNED 1111
#define IDM_OPT_OUTPUT_ASCII 1120
#define IDM_OPT_OUTPUT_UTF8 1121
#define IDM_OPT_OUTPUT_SJIS 1122
#define IDM_OPT_OUTPUT_HEX 1123
#define IDM_OPT_INPUT_UTF8 1130
#define IDM_OPT_INPUT_SJIS 1131
#define IDM_OPT_INPUT_HEX 1132
#define IDM_OPT_NOINPUT_ERROR 1140
#define IDM_OPT_NOINPUT_ZERO 1141
#define IDM_OPT_NOINPUT_FF 1142
#define IDM_OPT_INTOVF_ERROR 1150
#define IDM_OPT_INTOVF_WRAPAROUND 1151
#define IDM_OPT_PTROVF_ERROR 1160
#define IDM_OPT_PTROVF_WRAPAROUND 1161
#define IDM_OPT_WORDWRAP 1170
#define IDM_ABOUT 1200

#endif
