#ifndef DEF_H_
#define DEF_H_

#define WND_CLASS_NAME L"brainfuck-main"
#define APP_NAME L"Brain fuck"
#define APP_VERSION L"1.0"
#define APP_COPYRIGHT "(C) 2022 watamario15"
#define WM_APP_THREADEND WM_APP
#define IDT_RUN 1

#define VER_STR_COMPANYNAME "watamario15"
#define VER_STR_DESCRIPTION "Brainfuck interpreter for SHARP Brain"
#define VER_STR_FILEVERSION 1, 0, 0, 0
#define VER_STR_APPNAME "Brain fuck"
#define VER_STR_COPYRIGHT "(C) 2022 watamario15"
#define VER_STR_ORIGINALFILENAME "Brainfuck.exe"
#define VER_STR_VERSION "1.0"

#define IDC_EDITOR 0
#define IDC_INPUT 1
#define IDC_OUTPUT 2
#define IDC_MEMVIEW 3
#define IDC_CMDBTN_FIRST 4
#define IDC_SCRKBD_FIRST 8

#define IDG_FROM 1
#define IDG_OK 2
#define IDG_CANCEL 3

#define IDM_FILE_NEW 1000
#define IDM_FILE_OPEN 1001
#define IDM_FILE_SAVE 1002
#define IDM_FILE_SAVE_AS 1003
#define IDM_FILE_EXIT 1004
#define IDM_OPT_MEMTYPE_SIGNED 1100
#define IDM_OPT_MEMTYPE_UNSIGNED 1101
#define IDM_OPT_OUTPUT_ASCII 1110
#define IDM_OPT_OUTPUT_UTF8 1111
#define IDM_OPT_OUTPUT_SJIS 1112
#define IDM_OPT_OUTPUT_HEX 1113
#define IDM_OPT_INPUT_UTF8 1120
#define IDM_OPT_INPUT_SJIS 1121
#define IDM_OPT_INPUT_HEX 1122
#define IDM_OPT_NOINPUT_ERROR 1130
#define IDM_OPT_NOINPUT_ZERO 1131
#define IDM_OPT_NOINPUT_FF 1132
#define IDM_OPT_INTOVF_ERROR 1140
#define IDM_OPT_INTOVF_WRAPAROUND 1141
#define IDM_OPT_DEBUG 1150
#define IDM_OPT_SPEED_FASTEST 1160
#define IDM_OPT_SPEED_1MS 1161
#define IDM_OPT_SPEED_10MS 1162
#define IDM_OPT_SPEED_100MS 1163
#define IDM_OPT_MEMVIEW 1170
#define IDM_OPT_HIGHLIGHT_MEMORY 1180
#define IDM_OPT_WORDWRAP 1190
#define IDM_ABOUT 1200

#endif
